In [10]:
import numpy as np
import scipy as sp
import sympy as sympy

### Question 16

In [17]:
import numpy as np
from scipy.linalg import expm

def build_generator_Q(k: int = 12):

    S = np.array([
        [-1.0,   1.0,  0.0,  0.0],
        [ 0.0,  -1.0,  0.9,  0.1],
        [ 0.0,   0.0, -1.0,  0.0],
        [ 0.0,   0.0,  0.0, -1.0/11.0]
    ])

    s = np.array([0.0, 0.0, 1.0, 1.0/11.0])
    alpha = np.array([1.0, 0.0, 0.0, 0.0])
    Sa = np.outer(s, alpha)

    n_levels = k
    dim = 4 * n_levels + 1
    absorbing = dim - 1

    Q = np.zeros((dim, dim))

    for n in range(n_levels):
        Q[4*n:4*n+4, 4*n:4*n+4] = S
        if n < n_levels - 1:
            Q[4*n:4*n+4, 4*(n+1):4*(n+1)+4] = Sa
        else:
            Q[4*n:4*n+4, absorbing] = s

    return Q
def prob_N_less_than_k(t_months: float = 60.0, k: int = 12) -> float:

    Q = build_generator_Q(k=k)
    dim = Q.shape[0]
    absorbing = dim - 1

    p0 = np.zeros(dim)
    p0[0] = 1.0

    pt = p0 @ expm(Q * t_months)
    return 1.0 - pt[absorbing]


t_months = 60.0  # 5 years
k = 12   
p = prob_N_less_than_k(t_months=t_months, k=k)
print(f"P(N(5 years) < 12) = {p:.6f}")


P(N(5 years) < 12) = 0.189481


### Question 17

In [ ]:
import scipy
S = np.array([
    [-1.0,  1.0,  0.0,  0.0],
    [ 0.0, -1.0,  0.9,  0.1],
    [ 0.0,  0.0, -1.0,  0.0],
    [ 0.0,  0.0,  0.0, -1.0/11.0]
])

alpha = np.array([[1.0, 0.0, 0.0, 0.0]]) 
one = np.ones((4, 1))

inv_minus_S = np.linalg.inv(-S)
pi_unnormalized = alpha @ inv_minus_S
pi = pi_unnormalized / (pi_unnormalized @ one)


t = 6.0  # months
surv_R = (pi @ scipy.linalg.expm(S * t) @ one)          # P(R > t)
prob_within_t = 1.0 - surv_R                    # P(R <= t)

print(f"P(next termination within {t} months) =", prob_within_t)


mu (months) = [[4.]]
P(next termination within 6.0 months) = [[0.78879698]]


### Question 18

In [ ]:
#Question 18
from sympy import *
l = latex(Matrix([[-1,1,0,0,0,0,0,0],[0,-1,0.9,0.1,0,0,0,0],[0.65,0,-1,0,0.35,0,0,0],[S(0.65)/11,0,0,-S(1)/11,S(0.35)/11,0,0,0],[0,0,0,0,-1,1,0,0],[0,0,0,0,0,-1,0.9,0.1],[1,0,0,0,0,0,-1,0],[S(1)/11,0,0,0,0,0,0,-S(1)/11]]))
print(l)

\left[\begin{matrix}-1 & 1 & 0 & 0 & 0 & 0 & 0 & 0\\0 & -1 & 0.9 & 0.1 & 0 & 0 & 0 & 0\\0.65 & 0 & -1 & 0 & 0.35 & 0 & 0 & 0\\0.0590909090909091 & 0 & 0 & - \frac{1}{11} & 0.0318181818181818 & 0 & 0 & 0\\0 & 0 & 0 & 0 & -1 & 1 & 0 & 0\\0 & 0 & 0 & 0 & 0 & -1 & 0.9 & 0.1\\1 & 0 & 0 & 0 & 0 & 0 & -1 & 0\\\frac{1}{11} & 0 & 0 & 0 & 0 & 0 & 0 & - \frac{1}{11}\end{matrix}\right]


eq 1.31

In [26]:
Q = np.array([[-1,1,0,0,0],[0,-1,0.9,0.1,0],[0,0,-1,0,1],[0,0,0,-1/11,1/11],[0,0,0,0,0]])
S = Q[:-1,:-1]
U = np.linalg.inv(-S)
alpha = np.array([1,0,0,0])
one = np.ones((4,1))
t_mean = alpha @ U @ one
t_mean

array([4.])

In [30]:
1-alpha @ sp.linalg.expm(S*4) @ one

array([0.70271186])

In [43]:
S

array([[-1.        ,  1.        ,  0.        ,  0.        ],
       [ 0.        , -1.        ,  0.9       ,  0.1       ],
       [ 0.        ,  0.        , -1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.09090909]])

In [28]:
import numpy as np

S_big = np.kron(np.eye(12), S)

alpha_big = np.zeros((1, S_big.shape[0]))
one_big = np.ones((S_big.shape[0], 1))

1-alpha_big @ sp.linalg.expm(S_big*60) @ one_big

TypeError: unsupported operand type(s) for *: 'float' and 'SingletonRegistry'

In [ ]:
1-alpha @ sp.linalg.expm(S*4) @ one